spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: false
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host:
    port:
    username:
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true